config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Gemini controller
  get "tag_selector", to: "gemini#tag_selector"
  get "suggest_exercises", to: "gemini#suggest_exercises"
  get "suggest_workout", to: "gemini#suggest_workout"

  resources :workouts, only: [:index, :create, :show, :destroy] do
    member do
      get 'evaluate_workout', to: "workouts#evaluate_workout"
      post 'suggest_exercise_based_on_type', to: "workouts#suggest_exercise_based_on_type"
      post "suggest_workout_based_on_type", to: "workouts#suggest_workout_based_on_type"
    end

    resources :exercises do
      get "evaluate_exercise", to: "exercises#evaluate_exercise"
      resources :exercise_sets, except: [:show]
    end
  end
  get "my_workouts", to: "workouts#my_workouts"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/workout.rb
class Workout < ApplicationRecord
    include GeminiAssistant

    belongs_to :user
    has_many :exercises, dependent: :destroy

    validates :user, presence: true

    scope :with_exercises, -> { Workout.includes(:user).where.not(exercises: { id: nil }).distinct }
    
    before_create :set_date

    def gemini_response_html
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        markdown.render self.gemini_response
    end

    private
    def set_date
        self.date = self.created_at if self.date.nil?
    end
end

app/controllers/workouts_controller.rb
include GeminiAssistant

class WorkoutsController < ApplicationController
    before_action :authenticate_user!, except: %i[ index ]
    before_action :set_workout, only: %i[ show destroy evaluate_workout suggest_exercise_based_on_type suggest_workout_based_on_type ]
    before_action :check_author, only: %i[destroy evaluate_workout suggest_exercise_based_on_type suggest_workout_based_on_type]

    def index
        # Select Workouts that have exercises in them
        @pagy, @workouts = pagy(Workout.includes(:user, :exercises).where.not(exercises: { id: nil }).distinct)
    end

    def create
        @workout = Workout.new
        @workout.user = current_user

        if @workout.save
            flash[:notice] = "Workout created!"
            redirect_to url_for(controller: 'workouts', action: 'my_workouts', params: {workout_id: @workout.id})
        else
            flash[:alert] = "Workout failed to create!"
            redirect_to my_workouts
        end
    end

    def show
        @exercises = @workout.exercises.order(created_at: :desc)
    end

    def destroy
        @workout.destroy!
    
        respond_to do |format|
          format.html { redirect_to my_workouts_path, notice: "Workout was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    def my_workouts
        @workouts = current_user.workouts
    end

    def evaluate_workout
        @workout.update(gemini_response: GeminiAssistant.evaluate_workout(@workout.id))
    end

    def suggest_exercise_based_on_type
        response = GeminiAssistant.suggest_exercise_based_on_type(params[:prompt], @workout.exercises.map {|exercise| "name: #{exercise.name}, description: #{exercise.description}"}.join(';'))

        @selected_tags = params[:prompt]

        rc = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        @html_response = rc.render response
    end

    def suggest_workout_based_on_type
        response = GeminiAssistant.suggest_workout_based_on_type(params[:prompt], @workout.exercises.map {|exercise| "name: #{exercise.name}, description: #{exercise.description}"}.join(';'))
        @selected_tags = params[:prompt]
        
        rc = Redcarpet::Markdown.new(Redcarpet::Render::HTML, hard_wrap: true)
        @html_response = rc.render response
    end

    private
    def set_workout
        @workout ||= Workout.find params[:id]
    end

    def check_author
        @workout ||= Workout.find params[:id]
        redirect_to my_workouts_path if current_user != @workout.user
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_index_nav.html.erb
<div class="fixed bottom-0 left-0 w-full h-[40px] bg-gray-600">
    <div class="p-2 w-full flex justify-between">
        <span class="flex-1">
            <% if @pagy.prev %>
                <%= link_to workouts_path(page: @pagy.prev), class: "flex items-center gap-2" do %>
                    <i class="fa-solid fa-angles-left w-[15px] h-[15px] block"></i>
                    <span>Previous Page</span>
                <% end %>
            <% else %>
                <span></span>
            <% end %>
        </span>

        <div class="hidden md:block">
            <%== pagy_info @pagy %>
        </div>

        <span class="flex-1 flex justify-end">
            <% if @pagy.next %>
                <%= link_to workouts_path(page: @pagy.next), class: "flex items-center gap-2 text-right" do %>
                    <span>Next Page</span>
                    <i class="fa-solid fa-angles-right w-[15px] h-[15px] block"></i>
                <% end %>
            <% else %>
                <span></span>
            <% end %>
        </span>
    </div>
</div>

app/views/workouts/_my_workouts_link.html.erb
<%= link_to my_workouts_path, class: "btn-primary" do %>
    <span>View Your Workouts</span>
    <span>
        <i class="fa-solid fa-eye"></i>
        <i class="fa-regular fa-file"></i>
    </span>
<% end %>

app/views/workouts/_workout.html.erb
<div>
    <% if current_page? my_workouts_path %>
        <div class="mb-2">
            <%= form_with method: :post do |form| %>
                <%= render "application/tag_selector", form: form %>
                <div class="m-0 mb-6 md:mt-2">
                    <%= form.button class: "m-0 mt-2 btn-primary", data: { turbo_frame: "modal", turbo_prefetch: false }, formaction: suggest_exercise_based_on_type_workout_path(workout) do %>
                        Suggest Exercise
                    <% end %>
                    <%= form.button class: "m-0 mt-2 btn-primary", data: { turbo_frame: "modal", turbo_prefetch: false }, formaction: suggest_workout_based_on_type_workout_path(workout) do %>
                        Suggest Workout
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>

    <% if current_user == workout.user && current_page?(my_workouts_path) %>
        <%= turbo_frame_tag dom_id(workout, "exercise_form"), class: "[&[busy]]:blur-sm [&[busy]+div]:block" do %>
            <%= render "exercises/form", workout: workout, exercise: Exercise.new %>
        <% end %>
        <%= render "application/loading_spinner" %>
    <% end %>
    
    <%= render "workout_analysis", workout: workout if current_page?(my_workouts_path) %>

    <div class="p-2">
        <%= turbo_frame_tag dom_id(workout, "exercises"), src: workout_exercises_path(workout), loading: "lazy" do %>
            <%= render "application/loading_spinner", show: true %>
        <% end %>    
    </div>

    <% if current_user == workout.user && current_page?(my_workouts_path) %>
        <div class="my-2">
            <%= button_to workout, method: :delete, type: :button, data: { confirm: 'Are you sure?', turbo_confirm: "Are you sure?"}, class: "text-red-600 font-bold" do %>
                <span class="">Delete Workout</span>
                <i class="fa-regular fa-trash-can cursor-pointer"></i>
            <% end %>
        </div>
    <% end %>
</div>

app/views/workouts/_workout_analysis.html.erb
<div data-controller="dropdown" class="p-2">
    <%= button_tag data: { action: "click->dropdown#toggle"}, class: "link flex gap-0" do %>
        <i class="fa-solid fa-caret-right block w-[25px] h-[25px]" data-dropdown-target="rotatable"></i>
        <span>Toggle Workout Analysis</span>
    <% end %>

    <div class="relative pb-2 hidden bg-gray-600 p-2 mt-4" data-dropdown-target="toggleable">
        <%= link_to "Generate Workout Analysis", evaluate_workout_workout_path(workout.id), data: { turbo_frame: dom_id(workout) + "_evaluation", turbo_prefetch: false }, class: "btn-primary" %>
        <%= turbo_frame_tag dom_id(workout) + "_evaluation", class: "[&[busy]]:blur-sm [&[busy]+div]:block" do %>
            <div>
                <% if workout.gemini_response.present? %>
                    <h3 class="text-xl underline">Workout Analysis</h3>
                    <%= sanitize workout.gemini_response_html %>
                <% else %>
                    <p>Add exercises to this workout in order to analyze it!</p>    
                <% end %>
            </div>
        <% end %>
        
        <%= render "application/loading_spinner" %>
    </div>
</div>

app/views/workouts/_workouts_index_link.html.erb
<%= link_to workout_path(workout), class: 'btn-primary' do %>
    <span>
        View Workout
    </span>
    <div>
        <i class="fa-regular fa-eye"></i>
        <i class="fa-solid fa-dumbbell"></i>
    </div>
<% end %>

app/views/workouts/evaluate_workout.html.erb
<%= turbo_frame_tag dom_id(@workout) + "_evaluation" do %>
    <%= sanitize @workout.gemini_response_html %>
<% end %>

app/views/workouts/index.html.erb
<h1 class="page-header">Everyone's Workouts</h1>

<div class="mb-[40px]">
    <% @workouts.order(date: :desc).each_with_index do |workout, idx| %>
        <div class="mb-2">
            <h1><%= workout.date.strftime("%Y-%m-%d") %> by User <%= workout.user_id %></h1>
            <%= render "workout", workout: workout %>
        </div>
    <% end %>
</div>

<%= render "index_nav" %>

app/views/workouts/my_workouts.html.erb
<div class="inline-flex items-center gap-4">
    <h1 class="page-header">My Workouts</h1>
    <%= button_to workouts_path, method: :post, class:"page-header", title: "Create New Workout" do %>
        <span>
            <i class="fa-solid fa-square-plus"></i>
        </span>
    <% end %>
</div>

<div >
    <% @workouts.order(date: :desc).each do |workout| %>
        <div data-controller="dropdown">
            <div class="flex items-center gap-6 w-fit p-2 rounded-b-none <%= "active-workout" if params[:workout_id].to_i == workout.id %>" data-dropdown-target="activatable">
                <%= button_tag class: "text-xl text-blue-400 hover:underline flex items-center", data: { action: "click->dropdown#toggleAccordion" } do %>
                    <i class="fa-solid fa-caret-right block w-[25px] h-[25px]" data-dropdown-target="rotatable"></i>
                    <span><%= workout.date.strftime("%Y-%m-%d") %></span>
                <% end %>
            </div>
            
            <div class="<%= params[:workout_id].to_i == workout.id ? "active-workout" : "hidden" %> p-2 exercises rounded-t-none" id="workout-<%= workout.id %>" data-dropdown-target="toggleable activatable">
                <%= render "workout", workout: workout %>
            </div>
        </div>
    <% end %>
</div>

app/views/workouts/show.html.erb
<h1 class="page-header">View Workout</h1>

<%= render "workout", workout: @workout %>

<%= render "workouts/my_workouts_link" %>

app/views/workouts/suggest_exercise_based_on_prompt.html.erb
<%= turbo_frame_tag "modal" do %>
    <div class="p-2" data-controller="turbo-modal" data-action="click@window->turbo-modal#closeBackground" data-turbo-modal-target="modal">
        <p><%= sanitize @html_response %></p>

        <p><%= button_tag "Close", data: { action: "click->turbo-modal#hideModal" }, class: "btn-cancel" %></p>
    </div>
<% end %>

app/views/workouts/suggest_exercise_based_on_type.html.erb
<%= turbo_frame_tag "modal" do %>
    <div class="p-4" data-controller="turbo-modal" data-action="click@window->turbo-modal#closeBackground" data-turbo-modal-target="modal">
        <p class="mb-2"><strong class="font-bold">Selected Muscle Groups:</strong> <%= @selected_tags %></p>
        <h3 class="m-0"><strong class="font-bold">Suggestion:</strong></h3>
        <div class="mb-2"><%= sanitize @html_response %></div>

        <p><%= button_tag "Close", data: { action: "click->turbo-modal#hideModal" }, class: "btn-cancel" %></p>
    </div>
<% end %>

app/views/workouts/suggest_workout_based_on_type.html.erb
<%= turbo_frame_tag "modal" do %>
    <div class="p-4" data-controller="turbo-modal" data-action="click@window->turbo-modal#closeBackground" data-turbo-modal-target="modal">
        <p class="mb-2"><strong class="font-bold">Selected Muscle Groups:</strong> <%= @selected_tags %></p>
        <div class="mb-2 whitespace-pre-wrap flex flex-col leading-5 [&>p]:mb-2 border-t-2 pt-2"><%= sanitize @html_response %></div>

        <p><%= button_tag "Close", data: { action: "click->turbo-modal#hideModal" }, class: "btn-cancel" %></p>
    </div>
<% end %>