config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Gemini controller
  get "tag_selector", to: "gemini#tag_selector"
  get "suggest_exercises", to: "gemini#suggest_exercises"
  get "suggest_workout", to: "gemini#suggest_workout"

  resources :workouts, only: [:index, :create, :show, :destroy] do
    member do
      get 'evaluate_workout', to: "workouts#evaluate_workout"
      post 'suggest_exercise_based_on_type', to: "workouts#suggest_exercise_based_on_type"
      post "suggest_workout_based_on_type", to: "workouts#suggest_workout_based_on_type"
    end

    resources :exercises do
      get "evaluate_exercise", to: "exercises#evaluate_exercise"
      resources :exercise_sets, except: [:show]
    end
  end
  get "my_workouts", to: "workouts#my_workouts"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/views/application/_header.html.erb
<nav>
    <div class="gap-x-10 hidden md:flex justify-end mr-6 mt-6">
        <%= link_to tag_selector_path, class: "#{local_assigns[:class_name]} flex gap-2 items-center", data: { turbo_frame: "modal"} do %>
            <i class="fa-regular fa-lightbulb"></i>
            <span>Suggestions</span>
        <% end %>
        <%= render "header_links" %>
        <%= render "user_session_links" %>
    </div>

    <%= render 'header_dropdown' %>
</nav> 

app/views/application/_header_dropdown.html.erb
<div class="relative text-left md:hidden w-full flex justify-end mt-2 pr-2" data-controller="dropdown">
    <div class="flex gap-4">
        <div>
            <%= link_to tag_selector_path, data: { turbo_frame: "modal" } do %>
                <i class="fa-regular fa-lightbulb text-4xl"></i>
            <% end %>
        </div>
        <div>
            <i class="fa-solid fa-bars text-4xl" data-action="click->dropdown#toggle"></i>
        </div>
    </div>

    <div class="absolute right-0 z-10 mt-10 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden border-2" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1" data-dropdown-target="toggleable">
        <div class="py-1" role="none">
            <%= render "header_links", class_name: "block px-4 py-2 text-sm text-gray-700" %>
            <hr class="mb-4" />
            <%= render "user_session_links", class_name: "block px-4 py-2 text-sm text-gray-700" %>
        </div>
    </div>
</div>

app/views/application/_header_links.html.erb
<%= link_to "Home", root_path, class: local_assigns[:class_name] %>
<%= link_to "My Workouts", my_workouts_path, class: local_assigns[:class_name] %>
<%= link_to "Everyone's Workouts", workouts_path, class: local_assigns[:class_name] %>

app/views/application/_loading_spinner.html.erb
<div class='<%= local_assigns[:show] ? "block" : "hidden" %> z-30 m-auto w-[50px] h-[50px] p-2'>
    <i class="fa-solid fa-spinner fa-spin w-full h-full"></i>
</div>

app/views/application/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="turbo-modal" class="p-4" data-action="<%= local_assigns[:close_on_submit] ? "turbo:submit-end->turbo-modal#submitEnd" : "" %> click@window->turbo-modal#closeBackground [&[busy]:text-red-600]" data-turbo-modal-target="modal">
      <h1 class="page-header"><%= title %></h1>

      <%= yield %>
    
      <p><%= button_tag "Close", data: { action: "click->turbo-modal#hideModal" }, class: "btn-cancel" %></p>
  </div>
<% end %>

app/views/application/_tag_selector.html.erb
<div class="inline-flex gap-2 flex-wrap select-none" data-controller="tag">
    <%= form.hidden_field :prompt, data: { tag_target: "taglist" } %>
    <% Exercise::EXERCISE_TAGS.each do |tag| %>
        <div class="p-2 bg-blue-500 rounded-md cursor-pointer" data-action="click->tag#toggleTag">
            <%= button_tag tag, class: "pointer-cursor", type: :button %>
        </div>
    <% end %>
</div>

app/views/application/_user_session_links.html.erb
<% if user_signed_in? %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: local_assigns[:class_name] %>
<% end %>
<% if !user_signed_in? %>
    <%= link_to "Sign In", new_user_session_path, class: local_assigns[:class_name] %>
<% end %>