config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Gemini controller
  get "tag_selector", to: "gemini#tag_selector"
  get "suggest_exercises", to: "gemini#suggest_exercises"
  get "suggest_workout", to: "gemini#suggest_workout"

  resources :workouts, only: [:index, :create, :show, :destroy] do
    member do
      get 'evaluate_workout', to: "workouts#evaluate_workout"
      post 'suggest_exercise_based_on_type', to: "workouts#suggest_exercise_based_on_type"
      post "suggest_workout_based_on_type", to: "workouts#suggest_workout_based_on_type"
    end

    resources :exercises do
      get "evaluate_exercise", to: "exercises#evaluate_exercise"
      resources :exercise_sets, except: [:show]
    end
  end
  get "my_workouts", to: "workouts#my_workouts"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/exercise_set.rb
class ExerciseSet < ApplicationRecord
    belongs_to :exercise
    has_one :workout, through: :exercise
    has_one :user, through: :exercise

    validates_presence_of :exercise
    validate :validate_presence_of_reps_or_weight


    private

    def validate_presence_of_reps_or_weight
        fields = %i[ reps weight ]
        errors.add :base, "Either reps or weight must be present." if fields.all? {|field| self[field].blank? }
    end
end

app/controllers/exercise_sets_controller.rb
class ExerciseSetsController < ApplicationController
    before_action :authenticate_user!, except: %i[index]
    before_action :set_exercise
    before_action :set_workout
    before_action :set_exercise_set, only: %i[destroy edit update]
    before_action :check_author, except: [:index]
    
    
    def index
        @exercise_sets = @exercise.exercise_sets
    end
    
    def create
        @exercise_set = @exercise.exercise_sets.new(exercise_set_params)
        
        respond_to do |format|
            if @exercise_set.save
                format.turbo_stream
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def new
        @exercise_set = @exercise.exercise_sets.new
    end

    def destroy
        @exercise_set.destroy

        respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.remove(@exercise_set)}
        end
    end

    def update
        respond_to do |format|
            if @exercise_set.update(exercise_set_params)
                format.turbo_stream
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    private

    def exercise_set_params
        params.require(:exercise_set).permit(:reps, :weight, :weight_unit)
    end

    def set_exercise
        @exercise = Exercise.find_by_id(params[:exercise_id])

        if @exercise.blank?
            flash[:alert] = "That exercise doesn't exist."
            return redirect_to my_workouts_path
        end 
    end

    def set_workout
        @workout = Workout.find_by_id(params[:workout_id])

        if @workout.blank?
            flash[:alert] = "That workout doesn't exist."
            return redirect_to my_workouts_path
        end 
    end

    def set_exercise_set
        @exercise_set = ExerciseSet.find_by_id(params[:id])

        if @exercise_set.blank?
            flash[:alert] = "That exercise set doesn't exist."
            return redirect_to my_workouts_path
        end 
    end

    def check_author
        @workout ||= Workout.find params[:workout_id]

        redirect_to my_workouts_path if current_user != @workout.user
    end
end

app/helpers/exercise_sets_helper.rb
module ExerciseSetsHelper
end

app/views/exercise_sets/_exercise_set.html.erb
<div id="<%= dom_id exercise_set %>" class="mb-2">
    <%= turbo_frame_tag dom_id(exercise_set, "info") do %>
        <div class="flex gap-x-4">
            <p>Set: <%= "#{exercise_set.reps} reps" if exercise_set.reps %><%= ", " if exercise_set.reps && exercise_set.weight %><%= "#{exercise_set.weight} #{exercise_set.weight_unit}" if exercise_set.weight %> <%=  %></p>

            <% if current_user == workout.user && request.referrer == my_workouts_url %>
                <%= link_to edit_workout_exercise_exercise_set_path(workout, exercise, exercise_set) do %>
                    <i class="fa-solid fa-pencil"></i>
                <% end %>

                <%= button_to workout_exercise_exercise_set_path(workout, exercise, exercise_set), method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
                    <i class="fa-regular fa-trash-can"></i>
                <% end %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/exercise_sets/_form.html.erb
<%= form_with model: [workout, exercise, exercise_set], data: { controller: :form, action: "turbo:submit-end->form#clear" } do |f| %>
  <% if exercise_set.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise_set.errors.count, "error") %> prohibited this exercise set from being saved:</h2>

      <ul>
        <% exercise_set.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="flex items-end gap-x-2">
        <div class="basis-1/5 md:basis-14">
            <%= f.label :reps, class: "font-bold" %><br />
            <%= f.number_field :reps, class: "w-full h-8 py-0 px-1 " %>
        </div>
        <div class="basis-1/5 md:basis-24">
            <%= f.label :weight, class: "font-bold" %><br />
            <%= f.number_field :weight, class: "w-full h-8 py-0 px-1", step: ".25" %>
        </div>
        <div class="">
            <%= f.label :weight_unit, "Wt. Unit", class: "font-bold" %><br />
            <%= f.select :weight_unit, ["lbs", "g"], {}, class: "w-full h-8 py-0 px-1" %>
        </div>
        <div class="">
            <%= f.button type: :submit, class: 'btn-primary w-full h-8 py-0 px-1 m-0' do %>
                <% if exercise_set.new_record? %>
                    Add Set
                <% else %>
                    Update
                <% end %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/exercise_sets/create.turbo_stream.erb
<%= turbo_stream.prepend(dom_id @exercise, "exercise_sets") do %>
    <%= render "exercise_sets/exercise_set", workout: @workout, exercise: @exercise, exercise_set: @exercise_set %>
<% end %>

<%= turbo_stream.update(dom_id(@exercise, "exercise_set_form")) do %>
        <%= render "form", workout: @workout, exercise: @exercise, exercise_set: @exercise.exercise_sets.new %>
<% end %>

app/views/exercise_sets/edit.html.erb
<%= turbo_frame_tag dom_id(@exercise_set, "info") do %>
    <div class="bg-gray-900 rounded-sm p-2">
        <%= render "form", workout: @workout, exercise: @exercise, exercise_set: @exercise_set %>
        <%= link_to workout_exercise_exercise_sets_path(@workout, @exercise), class: "block mt-4" do %>
            <i class="fa-solid fa-ban text-red-800"></i>
            Cancel
        <% end %>
    </div>
<% end %>

app/views/exercise_sets/index.html.erb
<%= turbo_frame_tag dom_id(@exercise, "exercise_sets") do %>
    <% @exercise_sets.map do |exercise_set| %>
        <%= render "exercise_set", workout: @workout, exercise: @exercise, exercise_set: exercise_set %>
    <% end %>
<% end %>

app/views/exercise_sets/new.html.erb
<%= turbo_frame_tag dom_id(@exercise, "exercise_set_form") do %>
    <%= render "form", workout: @workout, exercise: @exercise, exercise_set: @exercise_set %>
<% end %>

app/views/exercise_sets/update.turbo_stream.erb
<%= turbo_stream.replace(@exercise_set) do %>
    <%= render "exercise_sets/exercise_set", workout: @workout, exercise: @exercise, exercise_set: @exercise_set %>
<% end %>