config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Gemini controller
  get "tag_selector", to: "gemini#tag_selector"
  get "suggest_exercises", to: "gemini#suggest_exercises"
  get "suggest_workout", to: "gemini#suggest_workout"

  resources :workouts, only: [:index, :create, :show, :destroy] do
    member do
      get 'evaluate_workout', to: "workouts#evaluate_workout"
      post 'suggest_exercise_based_on_type', to: "workouts#suggest_exercise_based_on_type"
      post "suggest_workout_based_on_type", to: "workouts#suggest_workout_based_on_type"
    end

    resources :exercises do
      get "evaluate_exercise", to: "exercises#evaluate_exercise"
      resources :exercise_sets, except: [:show]
    end
  end
  get "my_workouts", to: "workouts#my_workouts"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/controllers/exercises_controller.rb
include GeminiAssistant

class ExercisesController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_exercise, only: %i[ show edit update destroy ]
  before_action :set_workout
  before_action :check_author, except: [:index, :show]

  def index
    @exercises = @workout.exercises
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.workout_id = params[:workout_id]

    respond_to do |format|
      if @exercise.save
        format.turbo_stream
        format.html { redirect_to workout_url(@exercise.workout_id), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.turbo_stream
        format.html { redirect_to workout_exercise_url(@workout, @exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exercise.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to url_for(controller: 'workouts', action: 'my_workouts', params: {workout_id: @workout.id}), notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def evaluate_exercise
    @exercise = Exercise.find(params[:exercise_id])
    
    response = GeminiAssistant.evaluate_exercise @exercise

    @exercise.gemini_response = response

    respond_to do |format|
      if @exercise.save
        format.turbo_stream 
      else
        format.html { render plain: "Couldn't save the exercise"}
      end
    end
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def set_workout
      @workout = Workout.find params[:workout_id]
    end

    def exercise_params
      params.require(:exercise).permit(:name, :description, :date)
    end

    def check_author
      @workout ||= Workout.find params[:workout_id]
      redirect_to my_workouts_path if current_user != @workout.user
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <% if current_user == workout.user && request.referrer == my_workouts_url %>
    <%= turbo_frame_tag dom_id(exercise, "exercise_set_form") do %>
      <%= render "exercise_sets/form", workout: workout, exercise: exercise, exercise_set: ExerciseSet.new %>
    <% end %>
  <% end %>

  <div class="my-4">
    <%= turbo_frame_tag dom_id(exercise, "exercise_sets"), src: workout_exercise_exercise_sets_path(workout, exercise), loading: "lazy" %>
  </div>
  <p>
    <span class="font-bold">Name:</span>
    <%= exercise.name %>
  </p>

  <% if exercise.description.present? %>
    <p>
      <span class="font-bold">Description:</span>
      <%= exercise.description %>
    </p>
  <% end %>

  <% if current_user == workout.user && request.referrer == my_workouts_url %>
    <%= link_to "Evaluate Exercise", workout_exercise_evaluate_exercise_path(workout, exercise), data: { turbo_frame: dom_id(exercise, "evaluation"), turbo_stream: true}, class: "btn-primary" %>
  <% end %>

  <div>
    <%= turbo_frame_tag dom_id(exercise, "evaluation"), class: "[&[busy]]:blur-sm [&[busy]+div]:block" do %>
        <% if exercise.gemini_response.present? %>
          <%= sanitize exercise.gemini_response_html %>
        <% end %>
    <% end %>
    <%= render "loading_spinner" %>
  </div>

  <% if current_user == workout.user && request.referrer == my_workouts_url %>
    <div class="mb-4 mt-2">
      <div>
          <% unless true %>
            <%= render "exercises/exercises_show_link", workout: workout, exercise: exercise %>
          <% end %>
          <% if current_user == workout.user %>
            <%= render "exercises/exercises_edit_link", workout: workout, exercise: exercise %>
            <%= render "exercises/exercises_destroy_link", workout: workout, exercise: exercise %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/exercises/_exercise_info_link.html.erb
<div class="mb-4 border-2 p-2" data-controller="dropdown" id="<%= workout_exercise_path(workout, exercise) %>">
    <%= button_tag type: :button, class: "flex items-center cursor-pointer", data: { action: "click->dropdown#toggle"} do %>
        <i class="fa-solid fa-caret-right block w-[25px] h-[25px]" data-dropdown-target="rotatable"></i>
        <p id="<%= dom_id exercise, "info_link" %>"><%= exercise.name %></p>
    <% end %>
    <div data-dropdown-target="toggleable" class="hidden">
        <%= turbo_frame_tag dom_id(exercise), src: workout_exercise_path(workout, exercise), loading: "lazy" %>
    </div>
</div>

app/views/exercises/_exercises_destroy_link.html.erb
<%= button_to [workout, exercise], method: :delete, title: "Delete Exercise", data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, form_class: "inline-block mr-4 md:mr-2", type: :button, class: "link" do %>
    <i class="fa-regular fa-trash-can"></i>
    <% if local_assigns[:show_text] %>
        <span>Delete Exercise</span>
    <% end %>
<% end %>

app/views/exercises/_exercises_edit_link.html.erb
<%= link_to edit_workout_exercise_path(workout, exercise), class: "mr-4 md:mr-2 link", title: "Edit Exercise", data: { turbo_frame: 'modal', turbo_prefetch: false} do %>
    <i class="fa-solid fa-pencil"></i>

    <% if local_assigns[:show_text] %>
        <span>Edit Exercise</span>
    <% end %>
<% end %>

app/views/exercises/_exercises_show_link.html.erb
<%= link_to [workout, exercise], class: "link", title: "View Exercise" do %>
    <i class="fa-regular fa-eye"></i>
<% end %>

app/views/exercises/_form.html.erb
<%= form_with(model: [workout, exercise], data: { controller: "form", action: "turbo:submit-end->form#clear"}) do |form| %>
  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "e.g. Bicep Curls, Zumba, Swimming", class: "placeholder:text-sm w-full md:w-[unset]" %>
  </div>

  <div>
    <%= form.label :description, "Description (optional)", style: "display: block" %>
    <%= form.text_field :description, placeholder: 'e.g. Ran for 2 miles', class: "placeholder:text-sm w-full md:w-[unset]" %>
  </div>

  <div>
    <%= form.button type: :submit, class: "btn-primary mt-2 w-full justify-center md:w-[unset]" do %>
      <% if exercise.new_record? %>
        <span>Create Exercise</span>
        <div>
          <i class="fa-solid fa-square-plus"></i>
          <i class="fa-solid fa-dumbbell"></i>
        </div>
      <% else %>
        <span>Update Exercise</span>
        <div>
          <i class="fa-solid fa-circle-check"></i>
          <i class="fa-solid fa-dumbbell"></i>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/exercises/_modal_form.html.erb
<div class="relative">
  <%= turbo_frame_tag "modal", class: "" do %>
    <div data-controller="turbo-modal" class="p-4" data-action="turbo:submit-end->turbo-modal#submitEnd click@window->turbo-modal#closeBackground [&[busy]:text-red-600]" data-turbo-modal-target="modal">
      <h1 class="page-header"><%= title %></h1>
      <%= render "form", workout: @workout, exercise: @exercise %>
      <p><%= button_tag "Close", data: { action: "click->turbo-modal#hideModal" }, class: "btn-cancel" %></p>
    </div>
  <% end %>
</div>

app/views/exercises/create.turbo_stream.erb
<%= turbo_stream.prepend(dom_id(@workout, "exercises")) do %>
    <%= render "exercises/exercise_info_link", workout: @workout, exercise: @exercise %>
<% end %>

<%= turbo_stream.update(dom_id(@workout, "exercise_form")) do %>
    <%= render "form", workout: @workout, exercise: Exercise.new %>
<% end %>

app/views/exercises/destroy.turbo_stream.erb
<%= turbo_stream.remove(workout_exercise_path(@workout, @exercise)) %>

app/views/exercises/edit.html.erb
<%= render "modal_form", title: "Edit Exercise" %>

<br>

<div class="inline-flex flex-col">
  <%= render "exercises_destroy_link", workout: @workout, exercise: @exercise, show_text: true %>
  <%= render "workouts/workouts_index_link", workout: @workout %>
</div>

app/views/exercises/evaluate_exercise.turbo_stream.erb
<%= turbo_stream.update(dom_id(@exercise, "evaluation")) do %>
    <%= sanitize @exercise.gemini_response_html %>
<% end %>

app/views/exercises/index.html.erb
<div>
  <%= turbo_frame_tag dom_id(@workout, "exercises") do %>
    <% @exercises.order(created_at: :desc).each do |exercise| %>
      <%= render "exercise_info_link", workout: @workout, exercise: exercise %>
    <% end %>
  <% end %>
</div>

app/views/exercises/new.html.erb
<%= turbo_frame_tag dom_id(@workout, "exercise_form") do %>
  <%= render "form", workout: @workout, exercise: @exercise %>
<% end %>

<br />

<div>
  <%= render "workouts/workouts_index_link", workout: @workout %>
</div>

app/views/exercises/update.turbo_stream.erb
<%= turbo_stream.replace(@exercise) do %>
    <%= render "exercises/exercise", exercise: @exercise, workout: @workout %>
<% end %>

<%= turbo_stream.update(dom_id @exercise, "info_link") do %>
    <%= @exercise.name %>
<% end %>